[package]
name = "marfil"
version = "0.1.0"
authors = ["Roberto Vidal <jrvidal@tuenti.com>"]
edition = "2018"
exclude = ["*.mf"]

[dependencies]
lalrpop-util = "0.19.0"
regex = "1.3.9"
log = "0.4.11"
env_logger = "0.7.1"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

